# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    # - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -p 2 -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.add("JuMP"); Pkg.add("Ipopt"); Pkg.build("JuVI");  Pkg.test("JuVI", coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'cd(Pkg.dir("TrafficAssignment")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
